spring:
  devtools:
    restart:
      enabled: false
  application:
    name: request-management-system

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

logging:
  level:
    org.hibernate.SQL: debug

vaadin:
  launch-browser: true